---
title: "Kazuharu Yanagimoto"
author:
  firstname: Kazuharu
  lastname: Yanagimoto
  address: Graduate School of Economics, Kobe University, 2-1 Rokkodai-cho Nada-ku, Kobe, Hyogo Prefecture, 657-8501, Japan
  position: Associate Professor at Kobe University. Labor, Macro, and Family Economics
  contacts:
    - icon: fa envelope
      text: yanagimoto@econ.kobe-u.ac.jp
      url: "mailto:yanagimoto@econ.kobe-u.ac.jp"
    - icon: assets/icon/bi-house-fill.svg
      text: kazuyanagimoto.com
      url: https://kazuyanagimoto.com
    - icon: fa brands orcid
      text: 0009-0007-1967-8304
      url: https://orcid.org/0009-0007-1967-8304
    - icon: fa brands github
      text: kazuyanagimoto
      url: https://github.com/kazuyanagimoto
    - icon: fa brands x-twitter
      text: kazuyanagimoto
      url: https://twitter.com/kazuyanagimoto
    - icon: assets/icon/fa-google-scholar.svg
      text: Kazuharu Yanagimoto
      url: https://scholar.google.com/citations?user=kypV1CYAAAAJ
    - icon: assets/icon/si-bluesky.svg
      text: kazuyanagimoto.com
      url: https://bsky.app/profile/kazuyanagimoto.com
    - icon: fa brands linkedin
      text: Kazuharu Yanagimoto
      url: https://www.linkedin.com/in/kazuharu-yanagimoto
    - icon: assets/icon/si-zenn.svg
      text: Kazuharu Yanagimoto
      url: https://zenn.dev/nicetak
format: awesomecv-typst
brand:
  typography: 
    fonts:
      - family: Roboto
        source: google
        weight: [100, 400, 700]
      - family: Source Sans 3
        source: google
        weight: [100, 400, 700]
        style: [normal, italic]
  color:
    primary: "#516db0"
execute: 
  echo: false
  warning: false
---

```{r}
library(typstcv)
```

## Positions

```{r}
#| output: asis
read.csv(
  "data/position.csv",
  colClasses = c("character", "Date", "Date", "character", "character")
) |>
  format_date(end = "end", sort_by = "start") |>
  resume_entry(title = "title", description = "location")
```

## Education

```{r}
#| output: asis
educ <- read.csv(
  "data/education.csv",
  colClasses = c("character", "Date", "Date", "character", "character")
)

educ |>
  format_date(end = "end", sort_by = "start") |>
  resume_entry(title = "degree", description = "institution")
```

## Research

```{r}
research <- read.csv("data/research.csv")
```

### Working Papers

```{r}
#| output: asis
research[research$type == "working_paper", ] |>
  resume_entry(title = "title", description = "coauthors", date = "date")
```

## Conference Presentations

```{r}
#| output: asis

read.csv(
  "data/conference.csv",
  colClasses = c("character", "Date", "Date", "character", "character")
) |>
  format_date(sort_by = "start") |>
  resume_entry(title = "title")
```

## Research Experience

```{r}
#| output: asis

read.csv(
  "data/job.csv",
  colClasses = c("character", "character", "Date", "Date", "character")
) |>
  format_date(end = "end", sort_by = "start") |>
  resume_entry(description = "institution")
```

## Teaching Experience

```{r}
#| output: asis

read.csv(
  "data/teaching.csv",
  colClasses = c("character", "character", "Date", "Date", "character")
) |>
  format_date(end = "end", sort_by = "start") |>
  resume_entry(description = "institution")
```

## Other Experience

```{r}
#| output: asis

read.csv("data/other.csv") |>
  resume_entry(details = c("detail1", "detail2"))
```

## Research Grant

```{r}
#| output: asis

read.csv("data/grant.csv", colClasses = c("character", "character", "Date")) |>
  format_date(start = "year", date_format = "%Y", sort_by = "start") |>
  resume_entry(description = "amount")
```


## Scholarships

```{r}
#| output: asis

read.csv(
  "data/scholarship.csv",
  colClasses = c("character", "Date", "Date", "character", "character")
) |>
  format_date(end = "end", sort_by = "start") |>
  resume_entry()
```


## Skills

```{r}
#| output: asis
read.csv("data/skill.csv") |>
  resume_entry(title = "area", description = "skills")
```
