---
name: Kazuharu
surname: Yanagimoto
position: "Ph.D. Candidate"
address: "CEMFI, Calle Casado del Alisal 5, 28014 Madrid, Spain"
email: "kazuharu.yanagimoto@cemfi.edu.es"
github: nicetak
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 709970
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = "data.r")

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = degree,
    what = inst,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Professional and Research Experience

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = inst,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Scholarships

```{r HONORS}
honors %>%
  detailed_entries(
    with = accomplishment,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```

