on:
  push:
    branches: main

name: Render CV

jobs:
  render:
    name: Render CV
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Render CV
        run: Rscript -e 'rmarkdown::render("cv.Rmd", output_format = "vitae::awesomecv", output_dir = "docs/")'
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs